[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
[build]
# To enable Nodejs RS Driver only features from Rust driver.
rustflags = ["--cfg", "scylla_unstable"]
