# The goal of this workflow is to check if examples run without any errors
name: Run examples
env:
  DEBUG: napi:*
  APP_NAME: scylladb-javascript-driver
  PEDANTIC: true
"on":
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - '**'
jobs:
  build-and-run-examples:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: npm run build -- --target x86_64-unknown-linux-gnu
        node: [ 20, 22, 24, current ]
    name: Build and run examples - ${{ matrix.settings.target }} - node@${{ matrix.node }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup
        with:
          host: ${{ matrix.settings.host }}
          target: ${{ matrix.settings.target }}
          node-version: ${{ matrix.node }}
      - name: Build
        run: ${{ matrix.settings.build }}
        shell: bash
      # Scylla docker setup copied from https://github.com/scylladb/scylla-rust-driver/blob/main/.github/workflows/rust.yml
      - name: Setup 3-node Scylla cluster
        run: |
          sudo sh -c "echo 2097152 >> /proc/sys/fs/aio-max-nr"
          docker compose -f .github/docker-compose.yml up -d --wait
      - name: Install examples dependencies
        run: |
          cd examples
          npm i
      - name: Run all examples
        run: SCYLLA_URI=172.42.0.2:9042 npm run examples
      - name: Stop the cluster
        if: ${{ always() }}
        run: docker compose -f .github/docker-compose.yml stop
      - name: Print the cluster logs
        if: ${{ always() }}
        run: docker compose -f .github/docker-compose.yml logs
      - name: Remove cluster
        run: docker compose -f .github/docker-compose.yml down
